name: projectflutterapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  curved_navigation_bar: ^0.3.2
  flutter:
    sdk: flutter
  firebase_auth: ^0.8.3
  cloud_firestore: ^0.9.7+2
  provider: ^4.0.5
  flutter_spinkit: "^4.1.2"
  google_sign_in: ^4.0.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^0.17.2
  custom_switch_button: ^0.5.0
  image_picker: ^0.6.1+4
  flutter_slidable: "^0.5.4"
  sqflite: ^1.1.0
  path_provider: ^0.5.0+1
  fluttertoast: ^4.0.1
  flutter_spinkit: "^4.1.2"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/Icon_material_edit.svg
   - assets/images/Icon_people.svg
   - assets/images/Requests.svg
   - assets/images/Icon_awesome_hackerrank.svg
   - assets/images/backgroung1noor.png
   - assets/images/background1noor.svg
   - assets/images/background.svg
   - assets/images/background.png
   - assets/images/ic_task.svg
   - assets/images/ic_check.svg
   - assets/images/edit.svg
   - assets/images/close.svg
   - assets/images/share.svg
   - assets/images/circle_close.svg
   - assets/images/circle_close.png
   - assets/images/ic_back_arrow.svg
   - assets/images/ic_check_btn.svg
   - assets/images/time.svg
   - assets/images/ic_plus.svg
   - assets/images/ic_addtolist.svg
   - assets/images/ic_red.svg
   - assets/images/ic_blue.svg
   - assets/images/ic_green.svg
   - assets/images/ic_yellow.svg
   - assets/images/ic_orange.svg
   - assets/images/ic_redd.svg
   - assets/images/ic_bluee.svg
   - assets/images/ic_greenn.svg
   - assets/images/ic_yelloww.svg
   - assets/images/ic_imagepicker.svg
   - assets/images/blue_catg.svg
   - assets/images/red_catg.svg
   - assets/images/yellow_catg.svg
   - assets/images/green_catg.svg
   - assets/images/mov_catg.svg
   - assets/images/ic_middle.svg
   - assets/images/ic_friends.svg
   - assets/images/setting.svg
   - assets/images/ic_more.svg
   - assets/images/circle_share.svg
   - assets/images/ic_pen_edit.svg
   - assets/images/ic_share_friends.svg
   - assets/images/img_notasks.svg
   - assets/images/bottomNoTask.svg
   - assets/images/rating.svg
   - assets/images/bottomNoTask.svg
   - assets/images/score_stars.svg
   - assets/images/score_value.svg
   - assets/images/sore_items.svg
   - assets/images/bgwithout.png
   - assets/images/champion.svg
   - assets/images/google_signin_button.png
























    # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Segoe UI
     fonts:
       - asset: fonts/SegoeUI.ttf
       - asset: fonts/SegoeUI_Bold.ttf
         weight: 900
   - family: Rubik
     fonts:
       - asset: fonts/Rubik-Regular.ttf
   - family: segoepr
     fonts:
       - asset: fonts/segoepr.ttf
   - family: MyFlutterApp
     fonts:
       - asset: fonts/MyFlutterApp.ttf
   - family: AwesomeIcon
     fonts:
       - asset: fonts/AwesomeIcon.ttf

   - family: RequestsAndFriends
     fonts:
       - asset: fonts/RequestsAndFriends.ttf

   - family: RequestsIcon
     fonts:
       - asset: fonts/RequestsIcon.ttf

   - family: Edit
     fonts:
       - asset: fonts/Edit.ttf



  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
